version: '3.3'
services:
  rabbitmq-realworld:
    image: rabbitmq:management
    container_name: rabbitmq-realworld
    ports:
        - "15672:15672"
        - "5672:5672"
    networks:
        - default
    healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "5672" ]
        interval: 5s
        timeout: 15s
        retries: 1
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - default
    restart: on-failure
  realworld-spring:
    image: realworld
    container_name: realworld
    hostname : realworld
    restart: always
    depends_on:
      - rabbitmq-realworld
      - mariadb
    ports:
      - 8080:8080
    networks:
      - default
  #realworld-php:
  #  image: realworld-php
  #  container_name: realworld-php
  #  hostname : realworld-php
  #  restart: always
  #  depends_on:
  #    - rabbitmq-server
  #    - mariadb
  #  ports:
  #    - 8080:8080
  #  networks:
  #    - network   
    