server:
  servlet:
    context-path: /api

realworld:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 3000000
  rabbitmq:
    exchange: exchange
    queue: article
    routingKey: key

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: rabbitmq-realworld
    port: 5672
    username: guest
    password: guest